/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_demo_hdiffpatch_HDiffPatchUtil */

#ifndef _Included_com_demo_hdiffpatch_HDiffPatchUtil
#define _Included_com_demo_hdiffpatch_HDiffPatchUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_demo_hdiffpatch_HDiffPatchUtil
 * Method:    hpatchz
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_demo_hdiffpatch_HDiffPatchUtil_hpatchz
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
